sonar.projectKey=IntanNanda_test-flow
# sonar.organization=intannanda  <- enable this for SonarCloud, remove for self-hosted

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.spec.ts,node_modules/**,.next/**
sonar.coverage.exclusions=**/*
