sonar.projectKey=IntanNanda_test-flow
sonar.organization=intannanda

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.spec.ts,node_modules/**,.next/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
