"use server";

import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

export async function acceptInvite(formData: FormData) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const token = formData.get("token") as string;

  const { data: invite } = await supabase
    .from("team_invites")
    .select("*")
    .eq("token", token)
    .single();

  if (!invite) return;
  if (invite.expires_at && new Date(invite.expires_at) < new Date()) return;

  // Check if already a member
  const { data: existing } = await supabase
    .from("team_members")
    .select("id")
    .eq("team_id", invite.team_id)
    .eq("profile_id", user.id)
    .single();

  if (!existing) {
    await supabase.from("team_members").insert({
      team_id: invite.team_id,
      profile_id: user.id,
      role: invite.role,
    });
  }

  // Mark invite as accepted
  await supabase
    .from("team_invites")
    .update({ accepted: true })
    .eq("id", invite.id);

  redirect("/projects");
}

export async function sendInvite(formData: FormData) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated." };

  const teamId = formData.get("teamId") as string;
  const email = (formData.get("email") as string)?.trim().toLowerCase();
  const role = (formData.get("role") as string) || "member";

  if (!email) return { error: "Email is required." };

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 7); // 7-day expiry

  // token is auto-generated by the DB default
  const { data: invite, error } = await supabase
    .from("team_invites")
    .insert({
      team_id: teamId,
      email,
      role: role as "admin" | "member" | "viewer",
      invited_by: user.id,
      expires_at: expiresAt.toISOString(),
    })
    .select("token")
    .single();

  if (error) return { error: error.message };

  // TODO: send invite email via Resend with invite link:
  // `/invite/${invite.token}`
  console.log(`Invite link: /invite/${invite?.token}`);
}
